<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="3" ignored="0" total="5" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="1483" started-at="2021-11-02T22:57:41Z" finished-at="2021-11-02T22:57:43Z">
    <groups>
    </groups>
    <test name="DeleteCustomerTest" duration-ms="1454" started-at="2021-11-02T22:57:41Z" finished-at="2021-11-02T22:57:43Z">
      <class name="com.automation.APIautomationFramework.testcases.Stripe.DeleteCustomerTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.automation.APIautomationFramework.testcases.Stripe.DeleteCustomerTest@6f36c2f0]" name="setUp" is-config="true" duration-ms="397" started-at="2021-11-02T22:57:41Z" finished-at="2021-11-02T22:57:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="DeleteCustomer(java.util.Hashtable)[pri:0, instance:com.automation.APIautomationFramework.testcases.Stripe.DeleteCustomerTest@6f36c2f0]" name="DeleteCustomer" duration-ms="1395" started-at="2021-11-02T22:57:41Z" data-provider="data" finished-at="2021-11-02T22:57:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Runmode=Y, id=cus_HguK9iKn87CvrJ}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.automation.APIautomationFramework.testcases.Stripe.DeleteCustomerTest.DeleteCustomer(DeleteCustomerTest.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DeleteCustomer -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.automation.APIautomationFramework.testcases.Stripe.DeleteCustomerTest@6f36c2f0]" name="tearDown" is-config="true" duration-ms="0" started-at="2021-11-02T22:57:43Z" finished-at="2021-11-02T22:57:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.automation.APIautomationFramework.testcases.Stripe.DeleteCustomerTest -->
    </test> <!-- DeleteCustomerTest -->
    <test name="CreateCustomerTest" duration-ms="1483" started-at="2021-11-02T22:57:41Z" finished-at="2021-11-02T22:57:43Z">
      <class name="com.automation.APIautomationFramework.testcases.Stripe.CreateCustomerTest">
        <test-method status="SKIP" signature="CreateCustomerAPIInvalid(java.util.Hashtable)[pri:0, instance:com.automation.APIautomationFramework.testcases.Stripe.CreateCustomerTest@46d59067]" name="CreateCustomerAPIInvalid" duration-ms="12" started-at="2021-11-02T22:57:41Z" data-provider="data" finished-at="2021-11-02T22:57:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=java@way2automation.com, name=cus_HguK9iKn87CvrJ, Runmode=Y, description=Adding the Second customer in framework}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Test skipped since rumode is N]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Test skipped since rumode is N
at com.automation.APIautomationFramework.testcases.Stripe.CreateCustomerTest.CreateCustomerAPIInvalid(CreateCustomerTest.java:88)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateCustomerAPIInvalid -->
        <test-method status="FAIL" signature="CreateCustomerAPIValid(java.util.Hashtable)[pri:0, instance:com.automation.APIautomationFramework.testcases.Stripe.CreateCustomerTest@46d59067]" name="CreateCustomerAPIValid" duration-ms="1436" started-at="2021-11-02T22:57:41Z" data-provider="data" finished-at="2021-11-02T22:57:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=ishita@way2automation.com, name=Ishita Arora, Runmode=Y, description=Adding the forth Customer in framework}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.automation.APIautomationFramework.utilities.TestUtil.getJsonKeyValue(TestUtil.java:19)
at com.automation.APIautomationFramework.testcases.Stripe.CreateCustomerTest.CreateCustomerAPIValid(CreateCustomerTest.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateCustomerAPIValid -->
        <test-method status="SKIP" signature="CreateCustomerAPIValid(java.util.Hashtable)[pri:0, instance:com.automation.APIautomationFramework.testcases.Stripe.CreateCustomerTest@46d59067]" name="CreateCustomerAPIValid" duration-ms="1" started-at="2021-11-02T22:57:41Z" data-provider="data" finished-at="2021-11-02T22:57:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=java@way2automation.com, name=Rahul Arora, Runmode=N, description=Adding the Second customer in framework}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Test skipped since rumode is N]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Test skipped since rumode is N
at com.automation.APIautomationFramework.testcases.Stripe.CreateCustomerTest.CreateCustomerAPIValid(CreateCustomerTest.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateCustomerAPIValid -->
        <test-method status="FAIL" signature="CreateCustomerAPIValid(java.util.Hashtable)[pri:0, instance:com.automation.APIautomationFramework.testcases.Stripe.CreateCustomerTest@46d59067]" name="CreateCustomerAPIValid" duration-ms="1436" started-at="2021-11-02T22:57:41Z" data-provider="data" finished-at="2021-11-02T22:57:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=corporate@way2automation.com, name=Raman Arora, Runmode=Y, description=Adding the Third Customer in Framework}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.automation.APIautomationFramework.utilities.TestUtil.getJsonKeyValue(TestUtil.java:19)
at com.automation.APIautomationFramework.testcases.Stripe.CreateCustomerTest.CreateCustomerAPIValid(CreateCustomerTest.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateCustomerAPIValid -->
      </class> <!-- com.automation.APIautomationFramework.testcases.Stripe.CreateCustomerTest -->
    </test> <!-- CreateCustomerTest -->
  </suite> <!-- Suite -->
</testng-results>
